# Generated by Django 4.2.2 on 2023-06-18 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Photos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='Photos/%Y/%m/%d')),
                ('caption', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Car',
            fields=[
                ('Id', models.AutoField(primary_key=True, serialize=False)),
                ('Price', models.DecimalField(decimal_places=3, max_digits=12, null=True)),
                ('Brand', models.CharField(max_length=50, null=True)),
                ('Model', models.CharField(max_length=50, null=True)),
                ('cc', models.IntegerField(null=True)),
                ('Transmission', models.CharField(max_length=50, null=True)),
                ('Fuel', models.IntegerField(null=True)),
                ('Car_class', models.CharField(max_length=50, null=True)),
                ('Hp', models.IntegerField(null=True)),
                ('Year', models.IntegerField(null=True)),
                ('Photos', models.ManyToManyField(to='Cars.photos')),
            ],
        ),
    ]
