# Generated by Django 4.2.2 on 2023-06-18 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Cars', '0002_remove_photos_caption_alter_photos_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='Hp',
            field=models.IntegerField(max_length=5, null=True),
        ),
        migrations.RemoveField(
            model_name='car',
            name='Photos',
        ),
        migrations.AlterField(
            model_name='car',
            name='Year',
            field=models.IntegerField(max_length=4, null=True),
        ),
        migrations.DeleteModel(
            name='Photos',
        ),
        migrations.AddField(
            model_name='car',
            name='Photos',
            field=models.TextField(null=True),
        ),
    ]
